version: "2"
services: 
  w_alpha: 
    build: ./worker-node/
    container_name: w_alpha
    environment: 
      - workername=alpha
    networks: 
      worker_net: 
        aliases: 
          - alpha
    ports: 
      - "1831:8080"
    volumes: 
      - "./worker-node:/usr/src/app"
  w_beta: 
    build: ./worker-node/
    container_name: w_beta
    environment: 
      - workername=beta
    networks: 
      worker_net: 
        aliases: 
          - beta
    ports: 
      - "1832:8080"
    volumes: 
      - "./worker-node:/usr/src/app"
  w_service: 
    build: ./worker_service/
    command: sh
    stdin_open: true      
    tty: true
    container_name: w_service
    networks: 
      worker_net: 
        aliases: 
          - w_service
    ports: 
      - "80:80"
    volumes: 
      - "./worker_service:/usr/src/app"
    environment:
      - FLASK_APP=worker_service/__init__.py
      - FLASK_DEBUG=1
      - WORKER_COUNT=2 # depends of worker instance. [alpha, beta, gamma, delta]

networks: 
  worker_net: 
    driver: bridge



# Launch & Build a bunch containers with workers and one service for them
