# Launch & Build a bunch containers with workers and one service for them.
version: "3.7"
services: 
  main_node:
    build: ./main-node/
    command: python3.7 api-supreme.py
    tty: true
    container_name: main-node
    networks:
     - brise_network
    ports:
      - "49152:49152"
    depends_on:
      - "w_service"
    environment:
      - EXP_DUMP_NAME=undefined

  w_service:
    build: ./worker_service/
    command: python3 intro.py
    stdin_open: true
    tty: true
    container_name: w_service
    networks:
      brise_network:
        aliases:
          - w_service
    ports:
      - "49153:49153"
    environment:
      - FLASK_APP=worker_service/__init__.py
      - FLASK_DEBUG=1

  front-end:
    build: ./front-end/
    container_name: front-end
    tty: true
    networks:
     - brise_network
    ports:
      - "80:80"

  w_alpha:
    build: ./worker/
    container_name: w_alpha
    environment:
      - workername=alpha
    networks:
      - brise_network
    depends_on:
      - "w_service"

  w_beta:
    build: ./worker/
    container_name: w_beta
    environment:
      - workername=beta
    networks:
      - brise_network
    depends_on:
      - "w_service"

  w_gamma:
    build: ./worker/
    container_name: w_gamma
    environment:
      - workername=gamma
    networks:
      - brise_network
    depends_on:
      - "w_service"

networks:
  brise_network:
    driver: bridge
    name: brise_network
