# Launch & Build a bunch containers with workers and one service for them.
version: "2"
services: 
  main_node:
    build: ./main-node/
    command: python3 api-supreme.py
    tty: true
    container_name: main-node
    networks:
     - worker_net
    ports:
      - "49152:49152"
    depends_on:
      - "w_service"

  w_service:
    build: ./worker_service/
    command: python3 intro.py
    stdin_open: true
    tty: true
    container_name: w_service
    networks:
      worker_net:
        aliases:
          - w_service
    ports:
      - "49153:49153"
    environment:
      - FLASK_APP=worker_service/__init__.py
      - FLASK_DEBUG=1

  # front-end:
  #   build: ./front-end/
  #   container_name: front-end
  #   tty: true
  #   networks:
  #    - worker_net
  #   ports:
  #     - "80:80"

  w_alpha:
    build: ./worker/
    container_name: w_alpha
    environment:
      - workername=alpha
    networks:
      - worker_net

  w_beta:
    build: ./worker/
    container_name: w_beta
    environment:
      - workername=beta
    networks:
      - worker_net

  w_gamma:
     build: ./worker/
     container_name: w_gamma
     environment:
       - workername=gamma
     networks:
       - worker_net

networks:
  worker_net:
    driver: bridge
