# Launch & Build a bunch containers with workers and one service for them.
version: "3.7"
services: 
  main-node:
    build: ./main-node/
    tty: true
    container_name: main-node
    environment:
      - EXP_DUMP_NAME=undefined
    restart: on-failure
    network_mode: host

  event_service:
    build: ./event_service/
    stdin_open: true
    tty: true
    container_name: event-service
    network_mode: host
    restart: on-failure

  mongo-db:
    image: mongo:4.2.7
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=5V5Scp1E
    ports:
        - '27017:27017'
    container_name: mongo-db
    network_mode: host
    restart: on-failure

  worker_service:
    build: ./worker_service/
    stdin_open: true
    tty: true
    container_name: worker-service
    network_mode: host
    restart: on-failure

  front-end:
    build: ./front-end/
    container_name: front-end
    tty: true
    network_mode: host
    restart: on-failure

  worker:
    build: ./worker/
    network_mode: host
    restart: on-failure
